torch-cuda-fb.timestamp: torch-cuda-fb/Dockerfile torch-cuda-fb/Makefile torch-cuda.timestamp
	# arg1: final image name, arg2: build context directory
	helpers/dockerbuild ${USER}/torch-cuda-fb torch-cuda-fb
	touch torch-cuda-fb.timestamp

